name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v7
      - name: Install Node and PNPM
        uses: pnpm/setup@v2
      - name: Build
        run: pnpm build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
